/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junit3;

import junit3.user.User;

public class App {
    
    public static void main(String[] args) {
        System.out.println(User.builder("id", "DrWaka", "email@email").toString());
    }
}
